server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/driving_school_system?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver





